version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/configs/ghost.template:/etc/nginx/conf.d/ghost.template
      - ./data/nginx:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - ghost
    restart: always
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - ./ghost/content:/var/lib/ghost/content:z
      - ./ghost/volumes/config.development.json:/var/lib/ghost/config.development.json
      - ./ghost/volumes/config.production.json:/var/lib/ghost/config.production.json
    expose:
      - "3306"
      - "2368"
    env_file:
      - .env
    environment:
      NODE_ENV: ${ENVIRONMENT}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MYSQL_DATABASE_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: https://${APP_DOMAIN}
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PSD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
