version: '3.7'
services:
  ghost:
    image: ghost:latest
    container_name: ghost_dev
    restart: always
    ports:
      - "5727:2368"
    expose:
      - "2368"
    environment:
      url: http://localhost:5727
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: content/data/ghost-dev.db
    volumes:
        - ./ghost/content:/var/lib/ghost/content

  nginx:
    image: nginx:latest
    container_name: nginx_ghost_dev
    restart: always
    depends_on:
      - ghost
    ports:
        - "80:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf