version: '3.7'
services:
  ghost:
    image: ghost:latest
    container_name: ghost_dev
    restart: always
    ports:
      - "3001:2368"
    environment:
      url: http://localhost:3001
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: content/data/ghost-dev.db
    volumes:
        - ./ghost/content:/var/lib/ghost/content